[package]
name = "systest"
version = "0.1.0"
authors = ["Igor Gnatenko <ignatenko@redhat.com>"]
build = "build.rs"

[dependencies]
libsolv-sys = { path = "../libsolv-sys" }
libc = "0.2"

[build-dependencies]
ctest = "0.1"
cc = { version = "1.0", features = ["parallel"] }
